### ISSUE TITLE
扫描一次后，泄露信息未删除，在扫无法收到之前未删除的泄露内容

### ISSUE THREAD

**Issue by lazze** [FeeiCN/GSIL#11]
[GSIL] [WARNING] Get Content Exception: 404 {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3/repos/contents/#get-contents'} retrying...

[GSIL] [WARNING] Get Content Exception: The read operation timed out retrying...

[GSIL] [WARNING] Get Content Exception: [Errno -2] Name or service not known retrying...

[GSIL] [WARNING] Get Content Exception: 404 {'message': 'No commit found for the ref xxxxxxx', 'documentation_url': 'https://developer.github.com/v3/repos/contents/'} retrying...

使用过程中，一些相关报错 -。-

**Comment by FeeiCN** [comment]
1. 设计理念是扫描且报告过的内容不会重复报告了。如果想扫之前的内容，可以删除`~/.gsil/`目录。
2. 这些异常是预期内的，因为项目被删除导致的。
