### ISSUE TITLE
github开发模式限制

### ISSUE THREAD

**Issue by d4wner** [FeeiCN/GSIL#12]
报错如下，是否本project有办法配置超时时间和间隔时间，我暂时没找到：
```
You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.', 'documentation_url': 'https://developer.github.com/v3/#abuse-rate-limits'
```
建议作者可以加上~

**Comment by FeeiCN** [comment]
1. 可以通过Crontab控制扫描频率
2. 可以通过增加GitHub Token解决

**Comment by d4wner** [comment]
我那边是单条命令行运行的，仅花了3分钟。
config.gsil里面已经添加了github token，总不能同一个厂商拆成多个规则运行吧，那就麻烦了。

**Comment by FeeiCN** [comment]
1. 单条命令运行没问题，你最终触发他运行是不是通过crontab，crontab可以调整运行改命令的频率。
2. 规则不用变，只需要多增加几个token就可以了。多个token是可以扫一个规则的。
