### ISSUE TITLE
怎么获得某个企业的相关特征 

### ISSUE THREAD

**Issue by PhoenixAD** [FeeiCN/GSIL#13]

**Comment by fun1355** [comment]
@PhoenixAD 你怎么不让楼主把洞送给你呢。。。
楼主开源了代码，是欠了你钱了？

**Comment by FeeiCN** [comment]
项目初衷是给甲方企业监控自己泄露漏洞用的，如果你是为了学习技术可以参考我这篇文章思路。

http://papers.feei.cn/GitHub敏感信息泄露监控.html

**Comment by PhoenixAD** [comment]
@FeeiCN 多谢！
