### ISSUE TITLE
python2.7遇到编码错误

### ISSUE THREAD

**Issue by ggg-geyi** [FeeiCN/GSIL#18]
File "/Users/xxx/code/Python/gsil/gsil/gsil/engine.py", line 254, in codes
    logger.debug('C:{x}/{l}: {c}'.format(x=idx, l=codes_len, c=codes[idx]))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 3-7: ordinal not in range(128)

>>> print sys.getdefaultencoding()
ascii

改为utf-8

**Comment by FeeiCN** [comment]
建议使用Python3，目前没计划支持Python2

**Comment by ggg-geyi** [comment]
Python2.7 test passed
