### ISSUE TITLE
限流功能

### ISSUE THREAD

**Issue by linpengstc** [FeeiCN/GSIL#19]
执行程序出现了rate limit异常，
文章中有提到：虽然GitHub API也有频率限制，但他的文档中明确了频率限制的策略，我们可以通过做好频率控制避免触发GitHub API限制规则。
请问程序是否还未实现自动限流，还需要配合人工来判断规则数量等一些配置，防止程序执行时超出限制

**Comment by FeeiCN** [comment]
限流是根据token和规则数量来配置crontab频率实现的，如果觉得这样麻烦可以简单的通过配置多个token来实现。
