### ISSUE TITLE
rules.gsil: 扫描规则能否说明具体一点

### ISSUE THREAD

**Issue by newaynewlife** [FeeiCN/GSIL#20]
能否说明一下ext和mode的使用方法，是放在keyword的下一级么？

**Comment by tudouya** [comment]
@newaynewlife 我读了代码，感觉是的，您那边有什么进展么？
我也在做这方面相关的项目

**Comment by FeeiCN** [comment]
@newaynewlife @tudouya 
已更新例子
https://github.com/FeeiCN/GSIL/blob/master/rules.gsil.example

**Comment by xiaoyanguoke** [comment]
@newaynewlife @tudouya 我也在做相关的项目。。。。
@FeeiCN 多多指教

**Comment by xiaopopoxiao** [comment]
我也感觉这个rules可读性太差了，级别套得太多了，二级分类有用么？主要不就是三级那个反斜杠作为github的keyword

> {

    # 一级分类，一般使用公司名，用作开启扫描的第一个参数（python gsil.py test）
    "test": {
        # 二级分类，一般使用产品线
        "mogujie.com": {
            # 公司内部域名
            "\"mogujie.org\"": {
                # mode/ext默认可不填
                "mode": "normal-match",
                "ext": "php,java,python,go,js,properties"
            },
            # 公司代码特征
            "copyright meili inc": {},
            # 内部主机域名
            "yewu1.db.mogujie.host": {},
            # 外部邮箱
            "mail.mogujie.com": {}
        }
    }
}

**Comment by FeeiCN** [comment]
@xiaopopoxiao 当你是在大公司或者监测的目标非常大时就觉得有用了。

**Comment by AngieQ1** [comment]
[GSIL] [CRITICAL] get rules failed, rule types not found!
请问一下这个怎么解决？

**Comment by youxian-yx** [comment]
> 
> 
> [GSIL] [CRITICAL] get rules failed, rule types not found!
> 请问一下这个怎么解决？



> 
> 
> [GSIL] [CRITICAL] get rules failed, rule types not found!
> 请问一下这个怎么解决？

解决了吗，
