### ISSUE TITLE
rule问题

### ISSUE THREAD

**Issue by xiaoyanguoke** [FeeiCN/GSIL#22]
你好，我编写了一个规则文件，例如按照你写的rule.gsil.example模板。我举个例子，（我想搜索关键字username password）如下,不知道我写的是否正确？
{
    "csdn": {
        "csdn.com": {
            "\"username password\"": {
                "mode": "normal-match",
                "ext": "php,java,python,go,js,properties,c++,c"
            }
        }
    }
}

**Comment by FeeiCN** [comment]
`""username password"": {`
引号中有引号的话需要使用反斜杠进行转义

`"\"username password\"": {`
