### ISSUE TITLE
No module named 'github'

### ISSUE THREAD

**Issue by loganca** [FeeiCN/GSIL#24]
python3.5.3已执行pip3 install -r requirements.txt，设置完成后执行 python gsil.py test 报No module named 'github'，如何解决？

**Comment by FeeiCN** [comment]
`python -V`看看是不是3以上的版本。

**Comment by loganca** [comment]
![_20180323162446](https://user-images.githubusercontent.com/32835419/37818939-c5c53034-2eb6-11e8-8e3e-87e92724b3c1.png)

**Comment by loganca** [comment]
root@bogon:~/gsil# python
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
root@bogon:~/gsil# python gsil.py test
Traceback (most recent call last):
  File "gsil.py", line 20, in <module>
    from gsil import gsil
  File "/root/gsil/gsil/__init__.py", line 19, in <module>
    from .engine import Engine
  File "/root/gsil/gsil/engine.py", line 18, in <module>
    from github import Github, GithubException
ImportError: No module named 'github'

**Comment by FeeiCN** [comment]
那就是你GitHub包没装上，手动安装下缺失的包试试：`pip3 install pygithub`。
