### ISSUE TITLE
关于__init__.py的疑问

### ISSUE THREAD

**Issue by Hecbi** [FeeiCN/GSIL#26]
您好前辈，在阅读这个程序源码的时候，不清楚/gsil/__init__.py中 line105 
`if __name__ == '__main__':
    gsil()`
的作用，能否解释一下？

**Comment by FeeiCN** [comment]
@Hecbi 

这段代码是用来在CLI下执行`python __init__.py`时能执行`gsil()`的，最初本质是为了方便调试`__init__.py`中的方法的。
