### ISSUE TITLE
找不到“github”库

### ISSUE THREAD

**Issue by volts1983** [FeeiCN/GSIL#35]
gsil]# python3 gsil.py test
Traceback (most recent call last):
  File "gsil.py", line 20, in <module>
    from gsil import gsil
  File "/root/gsil/gsil/__init__.py", line 19, in <module>
    from .engine import Engine
  File "/root/gsil/gsil/engine.py", line 18, in <module>
    from github import Github, GithubException
ImportError: No module named 'github'
[ gsil]# python3 -m pip install github
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Collecting github
  Could not find a version that satisfies the requirement github (from versions: )
No matching distribution found for github

**Comment by volts1983** [comment]
只找到一个github3，是一个吗？
https://github3py.readthedocs.io/en/master/

**Comment by volts1983** [comment]
是这哥们的吗？
https://github.com/rubik/github.py

**Comment by FeeiCN** [comment]
用官方源
