### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by zuoshouzz** [FeeiCN/GSIL#37]
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)

**Comment by FeeiCN** [comment]
环境问题，本地ssl没有安装好，自行google

**Comment by dingn2** [comment]
I stumbled with this issue. If you're using macOS go to Macintosh HD > Applications > Python3.6 folder (or whatever version of python you're using) > double click on "Install Certificates.command" file.
