### ISSUE TITLE
总是触发abuse detection mechanism

### ISSUE THREAD

**Issue by y0rkl4u** [FeeiCN/GSIL#38]
现在总是触发abuse detection mechanism规则，总的只有几条规则，使用了多个token,并且cron一天只执行一次，也总是触发abuse detection mechanism规则，从日志上可以看到是远远没达到5000的限制的，一般才发几次请求就触发了，求解

**Comment by FeeiCN** [comment]
没遇到过，能复现吗？token可以给，我测试下

**Comment by FeeiCN** [comment]
用的新注册的号的token吗？可以尝试用正常使用的账号生成token
