### ISSUE TITLE
Code may be useless, do not skip, add to list to be reviewed!怎么不发邮件

### ISSUE THREAD

**Issue by LizzyTester** [FeeiCN/GSIL#51]
请问关键字搜索的结果提示这个， 但不发邮件
是否发邮件的规则是什么， 在那控制呢？ 麻烦帮解答下，多谢了！

**Comment by FeeiCN** [comment]
提示这个表示搜索到了一些仓库，但这些仓库都都判定为无用仓库。
你可以尝试换个测试都规则，比如用默认都mogujie.org，手动都跑一遍。
