### ISSUE TITLE
监控的范围有哪些; 这个项目

### ISSUE THREAD

**Issue by 0x210** [FeeiCN/GSIL#53]
主要是搜索域名相关的关键字查看呈现内容，再进行匹配告警返回么。我看[你的代码](https://github.com/FeeiCN/GSIL/blob/4cf77b721ae01eaf48941f7fed93cb8680c96f7d/gsil/__init__.py#L28:L37)主要结果就是从这个地方获取的是吧。

**Comment by FeeiCN** [comment]
关键字可以是任何特征
