### ISSUE TITLE
不能发送邮件到邮箱怎么解决

### ISSUE THREAD

**Issue by shihunshi** [FeeiCN/GSIL#56]
2019-07-02 17:11:18,486 [GSIL] [CRITICAL] Send mail failed
Traceback (most recent call last):
  File "/root/桌面/GSIL/gsil/notification.py", line 71, in notification
    s.login(mail, get('mail', 'password'))
  File "/usr/lib/python3.7/smtplib.py", line 730, in login
    raise last_exception
  File "/usr/lib/python3.7/smtplib.py", line 721, in login
    initial_response_ok=initial_response_ok)
  File "/usr/lib/python3.7/smtplib.py", line 642, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'Error: \xc7\xeb\xca\xb9\xd3\xc3\xca\xda\xc8\xa8\xc2\xeb\xb5\xc7\xc2\xbc\xa1\xa3\xcf\xea\xc7\xe9\xc7\xeb\xbf\xb4: http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256')

**Comment by shihunshi** [comment]
> 2019-07-02 17:11:18,486 [GSIL] [CRITICAL] Send mail failed
> Traceback (most recent call last):
> File "/root/桌面/GSIL/gsil/notification.py", line 71, in notification
> s.login(mail, get('mail', 'password'))
> File "/usr/lib/python3.7/smtplib.py", line 730, in login
> raise last_exception
> File "/usr/lib/python3.7/smtplib.py", line 721, in login
> initial_response_ok=initial_response_ok)
> File "/usr/lib/python3.7/smtplib.py", line 642, in auth
> raise SMTPAuthenticationError(code, resp)
> smtplib.SMTPAuthenticationError: (535, b'Error: \xc7\xeb\xca\xb9\xd3\xc3\xca\xda\xc8\xa8\xc2\xeb\xb5\xc7\xc2\xbc\xa1\xa3\xcf\xea\xc7\xe9\xc7\xeb\xbf\xb4: http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256')
> 2019-07-02 17:11:18,486 [GSIL] [CRITICAL] Send mail failed
> Traceback (most recent call last):
> File "/root/桌面/GSIL/gsil/notification.py", line 71, in notification
> s.login(mail, get('mail', 'password'))
> File "/usr/lib/python3.7/smtplib.py", line 730, in login
> raise last_exception
> File "/usr/lib/python3.7/smtplib.py", line 721, in login
> initial_response_ok=initial_response_ok)
> File "/usr/lib/python3.7/smtplib.py", line 642, in auth
> raise SMTPAuthenticationError(code, resp)
> smtplib.SMTPAuthenticationError: (535, b'Error: \xc7\xeb\xca\xb9\xd3\xc3\xca\xda\xc8\xa8\xc2\xeb\xb5\xc7\xc2\xbc\xa1\xa3\xcf\xea\xc7\xe9\xc7\xeb\xbf\xb4: http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256')

**Comment by FeeiCN** [comment]
@shihunshi 邮箱配置错误，要用授权码https://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256
