### ISSUE TITLE
不支持中文

### ISSUE THREAD

**Issue by xjdhu** [FeeiCN/GSIL#58]
logger.debug('N:{x}/{l}: {c}'.format(x=i_idx, l=codes_len, c=codes[i_idx]))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u5e74' in position 22: ordinal not in range(128)

**Comment by FeeiCN** [comment]
支持的，不要改动代码中的编码，直接在规则文件中增加中文规则。
