### ISSUE TITLE
“全部匹配”模式下，增加取后10行

### ISSUE THREAD

**Issue by BlackHole1** [FeeiCN/GSIL#6]
刚刚在翻译时，发现参数说明那块的`匹配说明`不太对，参数直接为中文了，会让使用者有点迷惑。

于是我翻了下源码，找到了`匹配关键行`和`匹配存在关键词的行及其上下3行`，但是却没有找到全部匹配。

我查看的地址: [https://github.com/FeeiCN/GSIL/blob/master/gsil/engine.py#L217-L272](https://github.com/FeeiCN/GSIL/blob/master/gsil/engine.py#L217-L272)

只有`only-match`和`normal-match`, 却没有`full-match`. 这是否是一个问题呢？

本想在翻译时直接剔除`全部匹配`，但是感觉不太合适，于是提了一个issues来向你求证

**Comment by FeeiCN** [comment]
全部匹配当时是存在的，后来实际用的过程中发现部分文件过大，导致邮件报告无法查看。
后来“全部匹配”就改为取文件的前20行了，https://github.com/FeeiCN/GSIL/blob/master/gsil/engine.py#L272

**Comment by BlackHole1** [comment]
那应该对文档进行修正，而不是沿用之前的文档说明。

个人感觉取前20行不太好，如果可以，应该加上取后10行。

还有一个问题，如果文件的行数只有几行，但是代码还是照样截取的话，会不会出错

**Comment by FeeiCN** [comment]
1. 对，文档需要更新下。
2. 再加上后10行这个点不错。
3. 不会报错的。

**Comment by BlackHole1** [comment]
问题已解决
