### ISSUE TITLE
get rules failed, rule types not found!

### ISSUE THREAD

**Issue by qiushui777** [FeeiCN/GSIL#60]
大家好，我运行了案例中的rule
`{
    "test": {
        "mogujie.com": {
            "\"mogujie.org\"": {
                "mode": "normal-match",
                "ext": "php,java,python,go,js,properties"
            }
        }
    }
}`

报了如下错误，
`[GSIL] [CRITICAL] get rules failed, rule types not found!`

我看到有人和我一样的错误，我想问下这个要怎么解决呢？

**Comment by alpha302** [comment]
重命名试试

**Comment by FeeiCN** [comment]
删掉配置文件，用原始的再试试
