### ISSUE TITLE
关于使用有些疑问

### ISSUE THREAD

**Issue by LostNF** [FeeiCN/GSIL#67]
我这边查看每天使用的定时任务的日志时发现，每次都是从1/300开始扫描的，然后每次都是扫描到200/300就停下了，之后几天的日志也是这样，虽然扫到相同会跳过，但是这样会一直有没扫到的内容，请问这个问题如何解决。

**Comment by FeeiCN** [comment]
你可以新建一个测试的仓库试试看看是否能扫到。
